name: Build & Deploy para Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci --legacy-peer-deps

      - name: Build Angular
        run: npm run build

      - name: Verificar credenciais FTP
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        run: |
          echo "Servidor: $FTP_SERVER"
          echo "Usuario: $FTP_USERNAME"

      - name: Deploy via CURL FTP
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          sudo apt-get install -y lftp
          lftp -d -u "$FTP_USERNAME","$FTP_PASSWORD" "ftps://$FTP_SERVER" <<'LFTP_EOF'
          set ssl:verify-certificate false
          ls
          bye
          LFTP_EOF
